---
- name: Copy Kibana YUM repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Kibana
  dnf:
    name: kibana
    state: present

- name: Configure kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^server.port:.*'
    line: "server.port: {{ kibana_port }}"
    state: present
  notify: Restart Kibana

- name: Set server.host to allow external access
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server.host:.*'
    line: 'server.host: "{{ kibana_host }}"'
    state: present
  notify: Restart Kibana

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started
