apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue
  namespace: argocd           # where ArgoCD is installed
spec:
  project: instana
  source:
    repoURL: 'https://github.com/konka-devops-lab/crud-kustomization.git' # your repo
    targetRevision: HEAD                                         # branch/tag
    path: overlays                                                  # path to chart inside repo
    helm:
      valueFiles:
        - dev/app/frontend/kustomization.yaml     # add whichever value files you need
  destination:
    server: 'https://kubernetes.default.svc' # cluster ArgoCD is in
    namespace: crud                  # target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
