apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mysql
  - ../../../base/redis
patches:
  - path: mysql-patch-statefulset.yaml
    target:
      kind: StatefulSet
      name: crud-mysql

  - path: mysql-service-patch.yaml
    target:
      kind: Service
      name: crud-mysql
      
  - path: external-secret-patch.yaml
    target:
      kind: ExternalSecret
      name: external-secret-mysql

  - path: redis-patch-statefulset.yaml
    target:
      kind: StatefulSet
      name: crud-redis

  - path: redis-patch-service.yaml
    target:
      kind: Service
      name: crud-redis