# MySQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-crud-mysql
  labels:
    environment: dev
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: crud-mysql
          image: 384570460482.dkr.ecr.ap-south-1.amazonaws.com/crud:mysql-v1
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: dev-mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard