apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-redis       # Must match base name
  labels:
    environment: dev
spec:
  template:
    metadata:
      labels:
        app: crud-redis   # Must match base label
        version: blue
        environment: dev
    spec:
      containers:
        - name: crud-redis
          image: redis:alpine3.22

  volumeClaimTemplates:
    - metadata:
        name: redis-storage   # Must match base PVC name
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi