apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-crud-redis
spec:
  template:
    metadata:
      labels:
        version: blue
        app: dev-crud-redis
    spec:
      containers:
        - name: crud-redis
          image: redis:alpine3.22

          volumeMounts:
            - name: dev-redis-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: dev-redis-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
