- name: Create alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Create install directory
  file:
    path: "{{ alertmanager_install_dir }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: '0755'

- name: Download alertmanager
  get_url:
    url: "{{ alertmanager_download_url }}"
    dest: /tmp/alertmanager.tar.gz

- name: Extract alertmanager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
    creates: "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64"

- name: Copy alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
  notify: restart alertmanager

- name: Create systemd service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start alertmanager
  systemd:
    name: alertmanager
    enabled: true
    state: started