# MySQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-mysql
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: crud-mysql
          image: siva9666/crud:mysql-v1
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard