- name: Create grafana user
  user:
    name: "{{ grafana_user }}"
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Create install directory
  file:
    path: "{{ grafana_install_dir }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    mode: '0755'

- name: Download Grafana Enterprise
  get_url:
    url: "{{ grafana_download_url }}"
    dest: /tmp/grafana.tar.gz

- name: Extract Grafana
  unarchive:
    src: /tmp/grafana.tar.gz
    dest: "{{ grafana_install_dir }}"
    remote_src: yes
    creates: "{{ grafana_install_dir }}/grafana-enterprise-{{ grafana_version }}.linux-amd64"

- name: Create systemd service for Grafana
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    mode: '0644'

- name: Set ownership of Grafana install directory
  file:
    path: "{{ grafana_install_dir }}/grafana-v{{ grafana_version }}"
    state: directory
    recurse: yes
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start Grafana
  systemd:
    name: grafana
    enabled: true
    state: started

- name: Create Grafana dashboards directory
  file:
    path: /opt/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'

- name: Copy custom dashboard JSON
  copy:
    src: dashboards/
    dest: /opt/grafana/dashboards/
    owner: grafana
    group: grafana
    mode: '0644'

- name: Copy Grafana dashboard provisioning config
  template:
    src: dashboard-provisioning.yml.j2
    dest: "{{ grafana_install_dir }}/grafana-v{{ grafana_version }}/conf/provisioning/dashboards/dashboard.yml"
    owner: grafana
    group: grafana
    mode: '0644'

- name: Create Grafana datasource directory
  file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'

- name: Add Prometheus as default datasource
  template:
    src: prometheus-datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: grafana
    group: grafana
    mode: '0644'

- name: Restart Grafana
  systemd:
    name: grafana
    state: restarted
    daemon_reload: yes