apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prod-external-secret-backend
spec:
  target:
    name: prod-backend-secret
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: backend
        property: MYSQL_USER

    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: backend
        property: MYSQL_PASSWORD
