apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-mysql
  namespace: crud
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-secret   # Kubernetes Secret name
  data:
    - secretKey: MYSQL_ROOT_PASSWORD    # Key inside K8s Secret
      remoteRef:
        key: mysql                      # Vault path relative to ClusterSecretStore.path
        property: MYSQL_ROOT_PASSWORD   # Vault property name
