---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-mysql
spec:
  serviceName: crud-mysql
  replicas: 1
  selector:
    matchLabels:
      app: crud-mysql
  template:
    metadata:
      labels:
        app: crud-mysql
    spec:
      containers:
        - name: crud-mysql
          image: crud-mysql:v1
          ports:
            - containerPort: 3306

          # Environment variables
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: MYSQL_ROOT_PASSWORD
          # Resources
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          # Liveness probe
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: crud-mysql
spec:
  selector:
    app: crud-mysql
  ports:
    - port: 3306
      targetPort: 3306
