apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
spec:
  template:
    spec:
      containers:
        - name: crud-backend
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-backend-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-backend-secret
                  key: MYSQL_PASSWORD