apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mysql

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      env: dev
      argocd: "true"
      version: blue
      app: crud-redis

images:
  - name: crud-mysql
    newName: siva9666/crud
    newTag: mysql-v1

patches:
  - path: storage-patch.yaml
    target:
      kind: StatefulSet
      name: crud-mysql
  - path: external-secret-patch.yaml
    target:
      kind: ExternalSecret
      name: external-secret-mysql