apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-mysql
spec:
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  template:
    spec:
      containers:
      - name: crud-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-crud-mysql-secret
              key: MYSQL_ROOT_PASSWORD