apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-mysql
spec:
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi