apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd           # where ArgoCD is installed
spec:
  project: instana
  source:
    repoURL: 'https://github.com/konka-devops-lab/instana-helmcharts.git' # your repo
    targetRevision: HEAD                                         # branch/tag
    path: instana-db                                                  # path to chart inside repo
    helm:
      valueFiles:
        - dev/rabbitmq.yaml
  destination:
    server: 'https://kubernetes.default.svc' # cluster ArgoCD is in
    namespace: instana                   # target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
