apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/redis

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      env: dev
      argocd: "true"
      version: blue
      app: crud-redis

patches:
  - path: storage-patch.yaml
    target:
      kind: StatefulSet
      name: crud-redis