apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/redis

namePrefix: dev-

# commonLabels:
#   org: KodeKloud

# labels:
#   - pairs:
#       env: dev
#       argocd: "true"
#       version: blue
#       app: crud-redis

commonLabels:
  env: dev
  argocd: "true"
  version: blue
  app: crud-redis

patches:
  - path: storage-patch.yaml
    target:
      kind: StatefulSet
      name: crud-redis