apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-redis
spec:
  volumeClaimTemplates:
    - metadata:
        name: dev-redis-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi