---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mini
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mini-namespace-admin
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mini-admin-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mini
    namespace: default
roleRef:
  kind: Role
  name: mini-namespace-admin
  apiGroup: rbac.authorization.k8s.io