apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-redis
spec:
  serviceName: crud-redis
  replicas: 1
  selector:
    matchLabels:
      app: crud-redis
  template:
    metadata:
      labels:
        app: crud-redis
    spec:
      containers:
        - name: crud-redis
          image: redis:alpine3.22
          ports:
            - containerPort: 6379

          # Resources
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"

          # Liveness probe
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - "6379" 
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - "6379" 
                - ping
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          volumeMounts:
            - name: redis-storage
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: crud-redis
spec:
  selector:
    app: crud-redis
  ports:
    - port: 6379
      targetPort: 6379
